# Generated by Django 2.0.6 on 2018-06-29 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180629_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', '남성'), ('x', '선택안함'), ('f', '여성')], max_length=1),
        ),
    ]
