# Generated by Django 2.0.6 on 2018-07-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180629_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('x', '선택안함'), ('f', '여성'), ('m', '남성')], max_length=1),
        ),
    ]
